CREATE TABLE IF NOT EXISTS REGISTERED_USER (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME varchar(64) NOT NULL CHECK (CHAR_LENGTH(USERNAME) >= 5) UNIQUE,
    EMAIL varchar(256) NOT NULL CHECK (CHAR_LENGTH(EMAIL) >= 3) UNIQUE,
    ENCODED_PASSWORD varchar(80) NOT NULL,
    ENABLED BOOL NOT NULL,
    CREATED_AT DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS USER_AUTHORITY (
    USER_ID BIGINT NOT NULL REFERENCES REGISTERED_USER(ID),
    AUTHORITY VARCHAR(64) NOT NULL,
    CONSTRAINT PK_USER_AUTHORITIES PRIMARY KEY (USER_ID, AUTHORITY)
);

CREATE TABLE IF NOT EXISTS POST (
    ID BIGSERIAL PRIMARY KEY,
    AUTHOR_ID bigint NOT NULL,
    TITLE VARCHAR(256) NOT NULL,
    --TODO: add banner image
    CONTENT TEXT NOT NULL
);