CREATE TABLE IF NOT EXISTS REGISTERED_USER
(
    ID                  BIGSERIAL PRIMARY KEY,
    USERNAME            varchar(64)  NOT NULL CHECK (CHAR_LENGTH(USERNAME) >= 5) UNIQUE,
    EMAIL               varchar(256) NOT NULL CHECK (CHAR_LENGTH(EMAIL) >= 3) UNIQUE,
    ENCODED_PASSWORD    varchar(80)  NOT NULL,
    ENABLED             BOOL         NOT NULL,
    CREATED_AT          DATE         NOT NULL DEFAULT CURRENT_DATE,
    LAST_MODIFIED_AT    DATE         NOT NULL DEFAULT CURRENT_DATE,
    LAST_MODIFIED_BY_ID bigint references REGISTERED_USER (ID)
);

CREATE TABLE IF NOT EXISTS USER_AUTHORITY
(
    USER_ID   BIGINT      NOT NULL REFERENCES REGISTERED_USER (ID),
    AUTHORITY VARCHAR(64) NOT NULL,
    CONSTRAINT PK_USER_AUTHORITIES PRIMARY KEY (USER_ID, AUTHORITY)
);

CREATE TABLE IF NOT EXISTS POST
(
    ID                  BIGSERIAL PRIMARY KEY,
    AUTHOR_ID           bigint              NOT NULL REFERENCES REGISTERED_USER (ID),
    TITLE               VARCHAR(256) UNIQUE NOT NULL CHECK (char_length(title) >= 8),
    --TODO: add banner image
--     TODO: ACTIVE     BOOLEAN             NOT NULL,
    CONTENT             TEXT                NOT NULL,
    CREATED_AT          DATE                NOT NULL DEFAULT CURRENT_DATE,
    CREATED_BY_ID       bigint              not null references REGISTERED_USER (ID),
    LAST_MODIFIED_AT    DATE                NOT NULL DEFAULT CURRENT_DATE,
    LAST_MODIFIED_BY_ID bigint references REGISTERED_USER (ID)
);

COMMENT ON COLUMN POST.CONTENT IS 'Post''s content in MD format';

CREATE TABLE IF NOT EXISTS POST_TAG
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(64) UNIQUE NOT NULL CHECK ( char_length(name) >= 1 ),
    DESCRIPTION VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS POST_TAG_REFERENCE
(
    POST_ID BIGINT REFERENCES POST (ID) ON DELETE CASCADE,
    TAG_ID  BIGINT REFERENCES POST_TAG (ID) ON DELETE CASCADE,
    CONSTRAINT PK_CONST PRIMARY KEY (POST_ID, TAG_ID)
);