CREATE TABLE IF NOT EXISTS REGISTERED_USER (
    ID IDENTITY,
    USERNAME varchar(64) NOT NULL CHECK (CHAR_LENGTH(USERNAME) > 8),
    EMAIL varchar(256) NOT NULL CHECK (CHAR_LENGTH(EMAIL) > 3),
    ENCODED_PASSWORD varchar(256) NOT NULL,
    CREATED_AT DATE NOT NULL DEFAULT CURRENT_DATE
);