POST {{url}}/user/register
Content-Type: application/json

{
  "username": "player123",
  "email": "player@gmail.com",
  "plainPassword": "12345678"
}

###
POST {{url}}/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "plainPassword": "admin"
}

###
GET {{url}}/user/1
Authorization: Bearer eyJraWQiOiJlNzAyZTYyZS03MGViLTQ1MDgtOWNkYy1jNmNkMTAxMmE1YzkiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC13ZWJzaXRlLWJsb2ctYXBpIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NTM1MjM0NDksInJvbGVzIjpbIkFETUlOIl19.Q7JQlnxiXcjUFLlETuuIhybbS1_hvP2Qv18gLBnOeTmMY6_XxR6ugrk52u3PBgc2Es-Rv309O2omtYO-3rIHFHtgBPCqgiAiwUmDCCHebALVJTHWsqE2VyMEQCbSM2hGKgSBvq8EFnO5DDIm8zpVqGwlzPRj0sSlVHbLBxaOyaLWLo_WmXfkzMyFnJ0nJ2zw4czDqQAFHGbGh2jNKVkMai2b7sjuj5tZWrAasmQ7MxJCMByLZkFg3IhmtzLrO3RtSdzrww1gdNsnw_1OJ11U6zT1_3UBkSwvigQuu2RuEeN28DH09o96dBa9u8BVluyIpkmzyh7dR2PG66ViC7Sl2A
