POST {{url}}/user/register
Content-Type: application/json

{
  "username": "player123",
  "email": "player@gmail.com",
  "plainPassword": "12345678"
}

###
POST {{url}}/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "plainPassword": "admin"
}

###
GET {{url}}/user/1
Authorization: Bearer eyJraWQiOiI2MjE1N2ViMC00NDA4LTRlMDMtYTMwOC1mNjIxYjkwMTJlYTAiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC13ZWJzaXRlLWJsb2ctYXBpIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NTM1NDU2MjIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiJdfQ.En1eimAVBZueD2UdNEWKqrVhI5SEjwLqtU5PnSpsPkBr1tzu7ulW-31K2RGU3CLBWG90tWTsFOvZe28qfV9zsXKYmJ00yFcXKUZUjxE1NH9H6AQ-K3uokkkFEn521BD9YFEUqCuQjZKCndcJOhMiW-Pd24AB3u-atsYfcd-uecP6WSOoZphs_RcFhnO2fOYhS7ItIJgJjXBTEcju6Ly5_UOfnAAIfOJkpvs1JnyRzY9nhNKeKTBbR4t0JWee-2yZIwzpgui_JvVxBOWrKw_CgerfOzM8L4nBF4WDyvv3srXuHVIR3ngFvetSbbmGlKS5xcTBVvO-yWfBoNOr5cGnng

